### ISSUE TITLE
Does not work for Flutter Web

### ISSUE THREAD

**Issue by myConsciousness** [dwyl/dart_multihash#7]
When I run Flutter for Web with this package, it occurs

```bash
../../../../.pub-cache/hosted/pub.dev/dart_multihash-0.2.0/lib/src/multihash/varint_utils.dart:17:28: Error: The integer literal
0x01FFFFFFFFFFFFFF can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 0x200000000000000 is the nearest value
that can be represented exactly.
    value = (value >> 7) & 0x01FFFFFFFFFFFFFF; // unsigned bit-right shift
```

**Comment by nelsonic** [comment]
@myConsciousness thank you very much for opening an issue to alert us to this. 🙏
Please give as much detail as you can regarding the version of Dart, Flutter, Dev Machine OS and Web Browser. 📜

@LuchoTurtle are you able to recreate this in a new Flutter Web Project? Or simply include the package in our **app** project that already has a Web deployment pipeline and see if you can get it to work? 🧑‍💻🤞🏼

**Comment by myConsciousness** [comment]
Hi @nelsonic ,

I tried it with

```bash
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792  • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
```

and platform is Google chrome.

This seems to be a problem limited to Flutter for Web, which runs in JavaScript.

**Comment by myConsciousness** [comment]
Maybe we need to use 0x200000000000000 for Web as error message showed 🤔

**Comment by myConsciousness** [comment]
It probably will not work in web browsers that work with JavaScript as long as this mask operation is defined. 

https://github.com/dwyl/dart_multihash/blob/21f74ddc434e44f2e87c7595c591caf14823bfd9/lib/src/multihash/varint_utils.dart#L17

Maybe what we should do is not to do the mask operation, but to ensure that the `value` is a less-than-53-bit integer.

**Comment by LuchoTurtle** [comment]
After merging #8 , confirmed it works on a `Flutter Web` file. Going to publish.

**Comment by LuchoTurtle** [comment]
New version has been published in https://pub.dev/packages/dart_multihash.

**Comment by nelsonic** [comment]
@LuchoTurtle were you able to add a regression test for this? 💭

**Comment by LuchoTurtle** [comment]
Created an issue for this in https://github.com/dwyl/dart_multihash/issues/9, will work on next 👍
